# Currently using default theme and settings provided by GitHub Pages.
# To customize the theme, uncomment the following line and replace 'THEME_NAME' with the desired theme.
# theme: jekyll-theme-THEME_NAME
